services:
  postgres:
    image: postgres:16
    container_name: heatmap-pg
    environment:
      POSTGRES_USER: heatmap
      POSTGRES_PASSWORD: heatmap
      POSTGRES_DB: heatmap
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heatmap -d heatmap"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: heatmap-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  pgdata:
