spring:
  application:
    name: heatmap
  profiles:
    default: dev

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,scheduledtasks"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
  info:
    git:
      mode: full

heatmap:
  cache:
    ttl-seconds: 300
  summary-refresh:
    enabled: false
    window-days: 7
    fixed-delay-ms: 600000
    initial-delay-ms: 10000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    root: INFO
