logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.puetsnao.heatmap: DEBUG

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%m %U %H" %s %b %D'
      rotate: true
      request-attributes-enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,scheduledtasks"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
  info:
    git:
      mode: full

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heatmap
    username: heatmap
    password: heatmap
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

heatmap:
  summary-refresh:
    enabled: true
    window-days: 7
    fixed-delay-ms: 600000
    initial-delay-ms: 5000
