logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.puetsnao.heatmap: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/heatmap
    username: heatmap
    password: heatmap
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
